services:
  app_proxy:
    environment:
      APP_HOST: campfire_server_1
      APP_PORT: 80
      PROXY_AUTH_ADD: 'false'
    container_name: campfire_app_proxy_1

  server:
    image: mauricewipf/campfire-umbrel:latest
    volumes:
      - ${APP_DATA_DIR}/data/storage:/rails/storage
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: ${APP_SEED}
      REDIS_URL: redis://campfire_redis_1:6379
      DISABLE_SSL: 'true'
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY:-}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY:-}
      SENTRY_DSN: ${SENTRY_DSN:-}
    depends_on:
      - redis
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/up" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      # https://once.com/campfire#requirements
      resources:
        limits:
          memory: 8G # 64G for up to 10,000 users
          cpus: '4' # 32 for up to 10,000 users
        reservations:
          memory: 2G
          cpus: '1'
    restart: on-failure
    container_name: campfire_server_1

  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --save 300 10 --save 900 100 --appendonly yes --loglevel warning
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    restart: on-failure
    container_name: campfire_redis_1
